In [1]:
import numpy as np
import sys

In [7]:
#initialise zero matrix
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [8]:
#initialise once matrix
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
#any other number
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [11]:
#to get random decimal numbers numbers
np.random.rand(3,3,1)

array([[[0.14569994],
        [0.53333288],
        [0.96859833]],

       [[0.68250284],
        [0.82386544],
        [0.17038058]],

       [[0.50138619],
        [0.84006013],
        [0.62343902]]])

In [18]:
#to ger random integer numbers
np.random.randint(10,size=(3,3))

array([[5, 1, 4],
       [0, 5, 4],
       [7, 0, 3]])

In [19]:
#to get a identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
#to repeat a array
c=np.array([[1,2,3]])
repeat=np.repeat(c,3,axis=0)
print(repeat)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
d=np.identity(5)
print(d)
e=np.identity(3)
print(e)
e[1,1]=100
d[1:-1,1:-1]=e
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[  1.   0.   0.   0.   0.]
 [  0.   1.   0.   0.   0.]
 [  0.   0. 100.   0.   0.]
 [  0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   1.]]


In [35]:
#copy array
e=np.array([2,3,4])
print(e)
f=e.copy()
f[2]=199
print(f)

[2 3 4]
[  2   3 199]


In [39]:
#mathametics
a=np.array([1,2,3,4])
a+=2
print(a)
a-=2
print(a)
a*=2
print(a)

[3 4 5 6]
[1 2 3 4]
[2 4 6 8]
