In [1]:
import numpy as np


In [6]:
#linear algebra
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [8]:
#find the determinant
a=np.identity(5)
np.linalg.det(a)

1.0

In [9]:
#more information is in https://numpy.org/doc/stable/reference/routines.linalg.html


statistics



In [11]:
statistics=np.array([1,2,3,4,5,6,7,8,9,10])
statistics

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.min(statistics)


1

In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.reshape((6,1))
b

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
#vertically stacking array
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#horizontal stack
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

insert data from the file


In [27]:
data=np.genfromtxt('data.txt',delimiter=",")
data=data.astype('int32')
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


boolean masking and data indexing

In [28]:
data>3


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
data[data>3]

array([4, 5, 6, 7, 8, 9])

In [31]:
a=np.array([1,2,3,4,5,6,7,8])
a[[2,3,4]]

array([3, 4, 5])

In [37]:
print(data)
np.any(data>5,axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ True,  True,  True])

In [38]:
((data>4) & (data<8))

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])