In [1]:
import numpy as np
import sys


In [3]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [4]:
#get a specific element a[r,i]
#to get 0
a[1,4]

0

In [5]:
#to get a specific row elements
a[1,:]

array([6, 7, 8, 9, 0])

In [6]:
#to get a specific column elements
a[:,1]

array([2, 7])

In [8]:
#to get a specific set of elements in a specific row or column
# not get 2,3,4 elements
a[0,1:4]

array([2, 3, 4])

In [9]:
#changing a value 
a[1,4]=10
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
#to get a element like 5
b[1,0,0]

5

In [15]:
# to change a element
#change 7,8 to 77 ,88
b[1,1,:]=[77,88]
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [77 88]]]
